### ISSUE TITLE
docker部署java.lang.IllegalArgumentException: Result Maps collection already contains value for com.jzt.jk.datart.core.mappers.ext.DashboardMapperExt.listByOrgId-String

### ISSUE THREAD

**Issue by yuipur** [running-elephant/datart#1116]
**Datart版本号**
1.0.0-deta.2

**错误描述**
docker部署java.lang.IllegalArgumentException: Result Maps collection already contains value for datart.core.mappers.ext.DashboardMapperExt.listByOrgId-String

**如何重现**
重现错误的步骤，例如：
1. docker部署不能正常启动
2.
Caused by: java.lang.IllegalArgumentException: Result Maps collection already contains value for datart.core.mappers.ext.DashboardMapperExt.listByOrgId-String
	at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:930) ~[mybatis-3.5.1.jar!/:3.5.1]
	at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:887) ~[mybatis-3.5.1.jar!/:3.5.1]
	at org.apache.ibatis.session.Configuration.addResultMap(Configuration.java:644) ~[mybatis-3.5.1.jar!/:3.5.1]
	at org.apache.ibatis.builder.MapperBuilderAssistant.addResultMap(MapperBuilderAssistant.java:208) ~[mybatis-3.5.1.jar!/:3.5.1]
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.applyResultMap(MybatisMapperAnnotationBuilder.java:240) ~[mybatis-plus-core-3.1.2.jar!/:3.1.2]
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parseResultMap(MybatisMapperAnnotationBuilder.java:214) ~[mybatis-plus-core-3.1.2.jar!/:3.1.2]
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parseStatement(MybatisMapperAnnotationBuilder.java:332) ~[mybatis-plus-core-3.1.2.jar!/:3.1.2]
	at com.baomidou.mybatisplus.core.MybatisMethodResolver.resolve(MybatisMethodResolver.java:42) ~[mybatis-plus-core-3.1.2.jar!/:3.1.2]
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parsePendingMethods(MybatisMapperAnnotationBuilder.java:134) ~[mybatis-plus-core-3.1.2.jar!/:3.1.2]
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parse(MybatisMapperAnnotationBuilder.java:125) ~[mybatis-plus-core-3.1.2.jar!/:3.1.2]
	at com.baomidou.mybatisplus.core.MybatisMapperRegistry.addMapper(MybatisMapperRegistry.java:82) ~[mybatis-plus-core-3.1.2.jar!/:3.1.2]
	at com.baomidou.mybatisplus.core.MybatisConfiguration.addMapper(MybatisConfiguration.java:104) ~[mybatis-plus-core-3.1.2.jar!/:3.1.2]
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:80) ~[mybatis-spring-2.0.1.jar!/:2.0.1]
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44) ~[spring-tx-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	... 28 more

**期望结果**
能够正常启动

**截图**
![image](https://user-images.githubusercontent.com/53717281/160960688-3bdf5003-7fec-439c-98d4-1499cefcda0c.png)

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: linux
- 数据源: mysql 5.7.0

**其他内容**
有关这个问题的任意其他内容

**Comment by scottsut** [comment]
`com.jzt.jk.datart.core` 你这是二开过吧？不说明清楚改过什么地方，谁能知道为什么报错。

**Comment by yuipur** [comment]
将mybatis换成mybatis-plus

**Comment by scottsut** [comment]
这个改动太大了，你们是有开发能力的，这样魔改产生的问题应该自己解决
