### ISSUE TITLE
定时任务发送邮件/企微通知报错

### ISSUE THREAD

**Issue by kiwi-field** [running-elephant/datart#1341]
**Datart Version**
1.0.0-beta.3   

**Describe the bug**
在定时任务页面点击发送企业微信任务或者邮件

**To Reproduce**
1.git clone  https://github.com/running-elephant/datart.git

2.切换到1.0.0-beta.3这个tag

3.在项目的根目录执行mvn compile

4.运行datart.DatartServerApplication启动类

5.在定时任务页面新建一个邮件的定时任务或者企业微信的定时任务
![image](https://user-images.githubusercontent.com/30741355/168418768-edf9682d-ae07-4b86-9ff1-84b5e71eb5b5.png)

6.点击立即发送
![image](https://user-images.githubusercontent.com/30741355/168418489-cb5fcc67-1e6d-46b6-af0a-c1821297026e.png)

7.后台报错信息
```
javax.script.ScriptException: ReferenceError: "process" is not defined in <eval> at line number 16518
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at datart.server.common.JsParserUtils.parseExecuteParam(JsParserUtils.java:21)
	at datart.server.job.ScheduleJob.doGetData(ScheduleJob.java:136)
	at datart.server.job.ScheduleJob.execute(ScheduleJob.java:100)
	at datart.server.service.impl.ScheduleServiceImpl.execute(ScheduleServiceImpl.java:198)
```

**Expected behavior**
邮件或者企业微信定时任务应该可以正常发送，后台日志不报错

**Screenshots**
![image](https://user-images.githubusercontent.com/30741355/168418865-4bc7c63a-604d-4bb2-aab6-7edef54376fd.png)

**Environmental details: (optional, depending on where the bug occurs)**
- 操作系统: Windows 10
- 数据库:  8.0.18
- jdk  1.8.0_321  
- idea   2022.1  
- maven 3.3.9    
- Node.js v16.14.2

**Comment by scottsut** [comment]
#1267
