### ISSUE TITLE
Question: How to setup scheduled task with manual cron input

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1522]
Hello, I tried to setup a weekly schedule but realized only possible with manual input.  I like to ask what value should the question mark take when using manual setup? As per cron syntax, that value should be the path to the script we want to trigger.

This is not specified in the user guide document.

![image](https://user-images.githubusercontent.com/100477931/175854238-ab042e3f-3620-47f9-b551-fa5c522e278e.png)

**Comment by clementchong** [comment]
Existing codes has week options logic but is not provided as an option on frontend. Is it feature removed or left out by mistake?

![image](https://user-images.githubusercontent.com/100477931/175870453-4d24ad60-0f09-490d-8ee9-89b09fb1eda4.png)

**Comment by scottsut** [comment]
We left out week option for some reason, it will be added in a later version.

**Comment by clementchong** [comment]
For manual input, do we leave the "?" as is? Meaning only specify the first 5 values for cron timing.

**Comment by scottsut** [comment]
No, the "?" is also part of the cron expression.

**Comment by scottsut** [comment]
It seems that there are several different implementations of cron expressions. Datart uses [quartz](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html) type.

**Comment by clementchong** [comment]
Thank you, it looks like we can leave the "?" as is.

This issue is tagged for volunteer, do you mean to add the week option?

**Comment by scottsut** [comment]
> Thank you, it looks like we can leave the "?" as is.
> 
> This issue is tagged for volunteer, do you mean to add the week option?

Yes.

**Comment by clementchong** [comment]
Somehow the existing scheduled task stopped working. My smtp is tested working. It was working before and I have not changed it. What could be the reason?

Even the demo site scheduled task feature is not working.

I like to make sure it is working before I make any change for testing.

![image](https://user-images.githubusercontent.com/100477931/176083861-0ad15498-3c79-46f4-a5a7-c0256752bc40.png)

![image](https://user-images.githubusercontent.com/100477931/176084326-ebd1cd61-4b60-480e-b9d4-7f86b3abc944.png)

**Comment by clementchong** [comment]
smtp online test is successful and test mail received. Not working from datart yet.

![image](https://user-images.githubusercontent.com/100477931/176085043-db4722f3-8d56-4f43-986a-3570329f9915.png)

**Comment by scottsut** [comment]
> 

It should be noted that the `password` configuration does not refer to the mailbox password, but the authorization code (may be this name, each mailbox is different)

**Comment by clementchong** [comment]
Yes, has been using Google app password. Is not mailbox password.

**Comment by scottsut** [comment]
Anything details in log file?

**Comment by clementchong** [comment]
2022-06-13 13:54:43.251 [https-jsse-nio-0.0.0.0-9293-exec-8] INFO  datart.server.service.impl.ScheduleServiceImpl : schedule started.
2022-06-13 13:54:43.255 [https-jsse-nio-0.0.0.0-9293-exec-8] INFO  datart.server.service.impl.ScheduleServiceImpl : Executing job [Weekly Summary,job type :EMAIL]
2022-06-13 13:54:50.180 [https-jsse-nio-0.0.0.0-9293-exec-8] ERROR datart.server.job.ScheduleJob : schedule execute error
javax.script.ScriptException: ReferenceError: "process" is not defined in <eval> at line number 16483
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at datart.server.common.JsParserUtils.parseExecuteParam(JsParserUtils.java:21)
	at datart.server.job.ScheduleJob.doGetData(ScheduleJob.java:133)
	at datart.server.job.ScheduleJob.execute(ScheduleJob.java:100)
	at datart.server.service.impl.ScheduleServiceImpl.execute(ScheduleServiceImpl.java:198)
	at datart.server.service.impl.ScheduleServiceImpl$$FastClassBySpringCGLIB$$a6988452.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at datart.server.service.impl.ScheduleServiceImpl$$EnhancerBySpringCGLIB$$97f16206.execute(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy186.execute(Unknown Source)
	at datart.server.controller.ScheduleController.execute(ScheduleController.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: jdk.nashorn.internal.runtime.ECMAException: ReferenceError: "process" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1442)
	at jdk.nashorn.internal.scripts.Script$Recompilation$545$644853IA$\^eval\_.L:5#n(<eval>:16483)
	at jdk.nashorn.internal.scripts.Script$Recompilation$544$646842A$\^eval\_.L:5#b(<eval>:16483)
	at jdk.nashorn.internal.scripts.Script$Recompilation$543$648338AAA$\^eval\_.L:5#R(<eval>:16483)
	at jdk.nashorn.internal.scripts.Script$Recompilation$539$653179AAA$\^eval\_.L:5#un#e#produce(<eval>:16483)
	at jdk.nashorn.internal.scripts.Script$Recompilation$538$843036AA$\^eval\_.L:5#updateBy(<eval>:21453)
	at jdk.nashorn.internal.scripts.Script$Recompilation$537$849342A$\^eval\_.L:5#getRuntimeDateLevelFields(<eval>:21625)
	at jdk.nashorn.internal.scripts.Script$Recompilation$533$857300AADA$\^eval\_.L:5#ChartDataRequestBuilder#buildGroups#groupColumns(<eval>:21790)
	at jdk.nashorn.internal.objects.NativeArray$12.forEach(NativeArray.java:1699)
	at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
	at jdk.nashorn.internal.objects.NativeArray.reduceInner(NativeArray.java:1702)
	at jdk.nashorn.internal.objects.NativeArray.reduce(NativeArray.java:1714)
	at jdk.nashorn.internal.scripts.Script$Recompilation$532$857004$\^eval\_.L:5#ChartDataRequestBuilder#buildGroups(<eval>:21781)
	at jdk.nashorn.internal.scripts.Script$Recompilation$519$867422$\^eval\_.L:5#ChartDataRequestBuilder#build(<eval>:21960)
	at jdk.nashorn.internal.scripts.Script$Recompilation$517$912302A$\^eval\_.L:5#getChartQueryData(<eval>:23040)
	at jdk.nashorn.internal.scripts.Script$Recompilation$516$913157AA$\^eval\_.L:5#getQueryData(<eval>:23049)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:641)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	... 99 common frames omitted
2022-06-13 13:54:50.194 [https-jsse-nio-0.0.0.0-9293-exec-8] INFO  datart.server.service.impl.ScheduleServiceImpl : job execute finished with failure

**Comment by scottsut** [comment]
> Somehow the existing scheduled task stopped working. My smtp is tested working. Datart scheduled task was working before and I have not changed it. What could be the reason?
> 
> Even the demo site scheduled task feature is not working.
> 
> I like to make sure it is working before I make any change for testing.
> 
> ![image](https://user-images.githubusercontent.com/100477931/176083861-0ad15498-3c79-46f4-a5a7-c0256752bc40.png)
> 
> ![image](https://user-images.githubusercontent.com/100477931/176084326-ebd1cd61-4b60-480e-b9d4-7f86b3abc944.png)

`mail` needs to be under `spring`.

**Comment by clementchong** [comment]
You have sharp eyes! Let me get the email sending working.

**Comment by clementchong** [comment]
> I realized my scheduler does not work, is there any other configuration required? I see the below mentioned NOT STARTED in my log. I run via "Execute Now" and email works.
> 
> 2022-06-30 22:23:01.973 [main] INFO org.quartz.core.SchedulerSignalerImpl : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl 2022-06-30 22:23:01.973 [main] INFO org.quartz.core.QuartzScheduler : Quartz Scheduler v.2.3.2 created. 2022-06-30 22:23:01.977 [main] INFO o.s.scheduling.quartz.LocalDataSourceJobStore : Using db table-based data access locking (synchronization). 2022-06-30 22:23:01.980 [main] INFO o.s.scheduling.quartz.LocalDataSourceJobStore : JobStoreCMT initialized. 2022-06-30 22:23:01.981 [main] INFO org.quartz.core.QuartzScheduler : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DatartScheduleCluster' with instanceId 'ubuntu1656598981939' Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally. NOT STARTED. Currently in standby mode. Number of jobs executed: 0 Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads. Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.
> 
> 2022-06-30 22:23:01.981 [main] INFO org.quartz.impl.StdSchedulerFactory : Quartz scheduler 'DatartScheduleCluster' initialized from an externally provided properties instance. 2022-06-30 22:23:01.981 [main] INFO org.quartz.impl.StdSchedulerFactory : Quartz scheduler version: 2.3.2

I see that there is a start button for each scheduled task. Now the scheduled task get triggered automatically as expected. However, there is a SQL error on column 'type'. Not sure if this is existing issue.

![image](https://user-images.githubusercontent.com/100477931/176709762-7209dfae-b25b-40d6-9569-86cbe9ed05e0.png)

![image](https://user-images.githubusercontent.com/100477931/176710381-590e2303-8ad5-44dc-b077-c8fd78bdd146.png)

Full log:

### Error querying database. Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list' ### The error may exist in datart/core/mappers/ext/ViewMapperExt.java (best guess) ### The error may involve datart.core.mappers.ext.ViewMapperExt.selectByPrimaryKey-Inline ### The error occurred while setting parameters ### SQL: select id, `name`, description, org_id, source_id, script, `type`, model, config, create_by, create_time, update_by, update_time, parent_id, is_folder, `index`, `status` from view where id = ? ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list' ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'

**Comment by clementchong** [comment]
Looks like this is the issue. Not sure if we can remove it.

![image](https://user-images.githubusercontent.com/100477931/176712481-87bf081f-cb2c-4c41-9620-4e37ca8b97da.png)

**Comment by scottsut** [comment]
> Looks like this is the issue. Not sure if we can remove it.
> 
> ![image](https://user-images.githubusercontent.com/100477931/176712481-87bf081f-cb2c-4c41-9620-4e37ca8b97da.png)

It is not recommended to use the code of dev branch in production !!

Database changes in the code of dev branch are not added to the migration script, which is the problem you mentioned above.

**Comment by clementchong** [comment]
ok, I would ignore this column change. Thank you!

**Comment by clementchong** [comment]
Quick question: Code is merged, would you prefer I always close the issues here on to leave them open? Not sure if you are tracking anything outside and then closing on your end.

**Comment by scottsut** [comment]
Never mind, you can always close issue after code is merged, other topics can be discussed in the new issue.

**Comment by clementchong** [comment]
ok thank you!
