### ISSUE TITLE
Hive数据源的数据视图中，列名自动带有DATART_VTABLE别名

### ISSUE THREAD

**Issue by q1139168548** [running-elephant/datart#1700]
**Datart版本号**
1.0.0-beta4

**错误描述**
Hive数据源的数据视图中，列名自动带有DATART_VTABLE别名，debug追踪至resultset.getMetaData()，发现此时的列名就是带有DATART_VTABLE前缀的，同样的环境下，查询Mysql和Clickhouse没有问题。

**截图**
![ea38eb9ec065211b4eb2e8fddc6bcbf](https://user-images.githubusercontent.com/48168645/180141381-1633cfdf-bb6f-4983-a0b1-57e46ae08347.png)

![QQ截图20220721140646](https://user-images.githubusercontent.com/48168645/180141411-4e42b919-cf54-410c-a050-6069c93ae9a0.png)

![6b99eb823424838826bf8277cd69a02](https://user-images.githubusercontent.com/48168645/180141549-d5152355-eb47-45d9-95b6-b79aaf0f3564.png)

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS:  Windows 10

**其他内容**
我是在本地开发环境启动的，启动的时候还报了一个错，但没有影响运行，不知道是否对这个问题有影响
 `javassist.NotFoundException: org.apache.calcite.sql.pretty.SqlPrettyWriter
	at javassist.ClassPool.get(ClassPool.java:430)
	at datart.core.common.ClassTransformer.transformSqlWriter(ClassTransformer.java:35)
	at datart.core.common.ClassTransformer.transform(ClassTransformer.java:29)
	at datart.DatartServerApplication.main(DatartServerApplication.java:12)`

**Comment by q1139168548** [comment]
![QQ截图20220721141123](https://user-images.githubusercontent.com/48168645/180141975-80bb7634-274c-4404-ae73-ca083f5a8431.png)

**Comment by q1139168548** [comment]
已找到解决办法，需要在hive新增一个配置项：
`hive.resultset.user.unique.column.names=false`
就不会在列名前添加表名了

**Comment by caojinlong-827** [comment]
> 

hive新增配置之后，还是不行。建议参考下面的方式。然后重新打包项目
https://gitee.com/running-elephant/datart/pulls/7/files
