### ISSUE TITLE
[BUG] 执行Presto数据查询报错: identifierQuote:不能为空,literalQuote:不能为空

### ISSUE THREAD

**Issue by MilkWangStudio** [running-elephant/datart#1912]
**Datart Version**
1.0.0-rc.1

**Describe the bug**
表现：第一次调用presto查询会报错
报错日志：ERROR datart.server.config.WebExceptionHandler : identifierQuote:不能为空,literalQuote:不能为空
报错位置：CustomSqlDialect.java:44

**To Reproduce**
1. 配置Presto数据源
2. 创建该数据源的数据视图，基于Sql查询
3. 执行第一次Select查询语句均会报错，刷新页面后会继续报错，不刷新页面，再次执行Sql不报错

**Expected behavior**
1. 第一次执行Select不报错

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: Any, MAC、Centos均会触发
 - Source Database: MySql 5.7
 - Browser: Any,  Chrome、FireFox均会触发

**Additional context**
目前的排障信息如下：
1. JdbcDataProviderAdapter.getSqlDialect 中的这一行报错： sqlDialect = getDefaultSqlDialect(driverInfo); 导致进入兜底逻辑
2. catch方法中的兜底逻辑里，读取了jdbc-driver.yml配置文件，该配置文件里没有配置"identifierQuote"、"literalQuote"参数，导致创建CustomSqlDialect对象时，参数校验过不去
4. getDefaultSqlDialect(driverInfo);外层的catch方法没有打印具体Exception，我增加了异常栈打印后重新测试，发现是javassist报错，Exception为ClassFormatError，详细信息：attempted  duplicate class definition
 for name: "org/apache/calcite/sql/dialect/prestosqldialect/Proxy
5. 第二次执行Select不报错，是getDefaultSqlDialect方法第一行设置了sqlDialog，因此后续执行时就不执行报错代码了，但是由于之前报错，configSqlDialect等配置代码未执行

**Screenshots**
图.1
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/15866249/185541392-15208f0f-5049-4830-9620-92565fe611ac.png">

图.2
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/15866249/185543940-2e0e2eec-8d3a-4100-a164-2a639e6e1736.png">

图.3
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/15866249/185544057-6beab2fe-b314-4179-8a19-94babf7a0c98.png">

图.4 JdbcDataProvider.loadDriverInfoFromResource 默认驱动配置
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/15866249/185544971-5285a94f-b858-4cb3-b929-5147fd2d4eed.png">

日志.1
```
2022-08-19 12:13:01.300 [http-nio-0.0.0.0-8080-exec-5] ERROR datart.server.config.WebExceptionHandler : literalQuote:不能为空,identifierQuote:不能为空
datart.core.base.exception.BaseException: literalQuote:不能为空,identifierQuote:不能为空
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at datart.core.base.exception.Exceptions.tr(Exceptions.java:52)
        at datart.core.base.exception.Exceptions.msg(Exceptions.java:28)
        at datart.core.common.BeanUtils.validate(BeanUtils.java:50)
        at datart.data.provider.calcite.dialect.CustomSqlDialect.createContext(CustomSqlDialect.java:44)
        at datart.data.provider.calcite.dialect.CustomSqlDialect.<init>(CustomSqlDialect.java:39)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.getSqlDialect(JdbcDataProviderAdapter.java:316)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.getQueryKey(JdbcDataProviderAdapter.java:185)
        at datart.data.provider.JdbcDataProvider.getQueryKey(JdbcDataProvider.java:213)
        at datart.data.provider.ProviderManager.execute(ProviderManager.java:112)
        at datart.server.service.impl.DataProviderServiceImpl.testExecute(DataProviderServiceImpl.java:209)
        at datart.server.controller.DataProviderController.testExecute(DataProviderController.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

日志.2
```
2022-08-19 12:05:23.394 [http-nio-0.0.0.0-8080-exec-4] ERROR d.d.provider.jdbc.adapters.JdbcDataProviderAdapter : DBType PRESTO mismatched, use custom sql dialect
javassist.CannotCompileException: by java.lang.ClassFormatError: loader (instance of  org/springframework/boot/web/embedded/tomcat/TomcatEmbeddedWebappClassLoader): attempted  duplicate class definition
 for name: "org/apache/calcite/sql/dialect/prestosqldialect/Proxy"
        at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:271)
        at javassist.ClassPool.toClass(ClassPool.java:1240)
        at javassist.ClassPool.toClass(ClassPool.java:1098)
        at javassist.ClassPool.toClass(ClassPool.java:1056)
        at javassist.CtClass.toClass(CtClass.java:1298)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.getDefaultSqlDialect(JdbcDataProviderAdapter.java:363)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.getSqlDialect(JdbcDataProviderAdapter.java:313)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.getQueryKey(JdbcDataProviderAdapter.java:185)
        at datart.data.provider.JdbcDataProvider.getQueryKey(JdbcDataProvider.java:213)
        at datart.data.provider.ProviderManager.execute(ProviderManager.java:112)
        at datart.server.service.impl.DataProviderServiceImpl.execute(DataProviderServiceImpl.java:275)
        at datart.server.service.impl.DataProviderServiceImpl.execute(DataProviderServiceImpl.java:214)
        at datart.server.controller.DataProviderController.execute(DataProviderController.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
```

**Comment by MilkWangStudio** [comment]
刷新页面才会再次报错，不刷新页面只会报一次错的代码找到了，因为每次刷新页面会调用一次接口：/api/v1/data-provider/providers

该接口是GET，查询Provider列表，但是不知道为什么每次调用都会重新初始化一次Provider缓存，我不是很理解这么做的目的。

> ServiceLoader.load(DataProvider.class); 这种SPI机制每次获取的都是新创建的实例，会导致执行sql时会重新初始化sqlDialect，但是Javassist的toClass无法重复调用 #1477 

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/15866249/185591289-a77d43b1-67b1-46f2-89ca-333693b581c3.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/15866249/185591349-1577287d-a39c-46f9-993a-ea035457803e.png">
