### ISSUE TITLE
下载视图会偶尔出错

### ISSUE THREAD

**Issue by chengyoucai** [running-elephant/datart#2085]
**Datart版本号**
[1.0.0-rc.0 release](https://github.com/running-elephant/datart/releases/tag/1.0.0-rc.0)

**错误描述**
下载视图会偶尔出错。规律不明显。

**如何重现**
无法稳定复现，但概率较高

**期望结果**
希望下载成功

**截图**
如果方便的话，添加一个截图帮助解释你的问题

**运行环境详情：(可选，取决于错误发生的具体位置)**

**其他内容**
后台错误日志：
2023-01-11 11:43:20,633 [] [pool-2-thread-33] ERROR (DownloadServiceImpl.java lambda$submitDownloadTask$0 99) - Download Task execute error
java.lang.NullPointerException: null
    at datart.server.service.impl.ViewServiceImpl.requirePermission(ViewServiceImpl.java:381) ~[classes!/:1.0.0-rc.0]
    at datart.server.service.impl.ViewServiceImpl.requirePermission(ViewServiceImpl.java:48) ~[classes!/:1.0.0-rc.0]
    at datart.server.service.BaseCRUDService.retrieve(BaseCRUDService.java:57) ~[classes!/:1.0.0-rc.0]
    at datart.server.service.BaseCRUDService$$FastClassBySpringCGLIB$$74d18de4.invoke(<generated>) ~[classes!/:1.0.0-rc.0]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.4.jar!/:5.3.4]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.4.jar!/:5.3.4]
    at datart.server.service.impl.ViewServiceImpl$$EnhancerBySpringCGLIB$$9097899f.retrieve(<generated>) ~[classes!/:1.0.0-rc.0]
    at datart.server.service.BaseService.retrieve(BaseService.java:88) ~[classes!/:1.0.0-rc.0]
    at datart.server.service.impl.DataProviderServiceImpl.execute(DataProviderServiceImpl.java:225) ~[classes!/:1.0.0-rc.0]
    at datart.server.service.impl.DataProviderServiceImpl.execute(DataProviderServiceImpl.java:215) ~[classes!/:1.0.0-rc.0]
    at datart.server.service.impl.AttachmentExcelServiceImpl.getFile(AttachmentExcelServiceImpl.java:44) ~[classes!/:1.0.0-rc.0]
    at datart.server.service.impl.DownloadServiceImpl.lambda$submitDownloadTask$0(DownloadServiceImpl.java:95) ~[classes!/:1.0.0-rc.0]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by qq443672581** [comment]
应该是报表下载比较慢，然后模拟登录超时了，然后 获取不当当前的userId

**Comment by qq443672581** [comment]
<img width="1195" alt="image" src="https://github.com/running-elephant/datart/assets/12726982/e6644f02-13e0-452d-b5d1-4377bd37e53e">
<img width="1198" alt="image" src="https://github.com/running-elephant/datart/assets/12726982/16f817e3-a570-444f-86d7-5b6173c3cadb">

**Comment by q1139168548** [comment]
升级一下新版本，已经解决了

**Comment by qq443672581** [comment]
> 

我现在用的 是 1.0.0-beta.3 版本 也有这个问题吗？

**Comment by q1139168548** [comment]
> > 
> 
> 我现在用的 是 1.0.0-beta.3 版本 也有这个问题吗？

会的，此Bug在1.0.0 rc2被修复，详见： #2018

**Comment by qq443672581** [comment]
> > > 
> > 
> > 
> > 我现在用的 是 1.0.0-beta.3 版本 也有这个问题吗？
> 
> 会的，此Bug在1.0.0 rc2被修复，详见： #2018

那请问直接升级 docker镜像版本到 rc2 就可以ma？数据库什么的都没用影响吧？

**Comment by q1139168548** [comment]
看一下release note ，应该没有break change

**Comment by qq443672581** [comment]
> 看一下release note ，应该没有break change

ok 非常感谢

**Comment by qq443672581** [comment]
> 看一下release note ，应该没有break change

还得请教下，我看我是不能升级的，翻牌器有不兼容问题。我想自己把补丁打到 我这个版本去。有什么文档吗，如何修改datart源码然后打出 docker镜像？
