### ISSUE TITLE
Error querying database

### ISSUE THREAD

**Issue by hongye007** [running-elephant/datart#2091]
**Datart Version**
v1.0.0-rc.1

**Describe the bug**
`2023-02-10 18:31:34.572 INFO  datart.server.service.impl.SourceServiceImpl : jdbc source schema job has been deleted 24676464ef0f4d068eae4f0eab22e91c - HDR
2023-02-10 18:31:34.728 ERROR datart.server.job.SchemaSyncJob : source schema parse error 
org.springframework.jdbc.UncategorizedSQLException: 
### Cause: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NullPointerException" [50000-200]
; uncategorized SQLException; SQL state [HY000]; error code [50000]; General error: "java.lang.NullPointerException" [50000-200]; nested exception is org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NullPointerException" [50000-200]
at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
at com.sun.proxy.$Proxy92.selectOne(Unknown Source)
at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160)
at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
at com.sun.proxy.$Proxy192.selectBySource(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
at com.sun.proxy.$Proxy193.selectBySource(Unknown Source)
at datart.server.job.SchemaSyncJob.upsertSchemaInfo(SchemaSyncJob.java:106)
at datart.server.job.SchemaSyncJob.execute(SchemaSyncJob.java:99)
at datart.server.service.impl.SourceServiceImpl.lambda$updateJdbcSourceSyncJob$2(SourceServiceImpl.java:445)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NullPointerException" [50000-200]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
at org.h2.message.DbException.get(DbException.java:194)
at org.h2.message.DbException.convert(DbException.java:347)
at org.h2.message.DbException.toSQLException(DbException.java:319)
at org.h2.message.TraceObject.logAndConvert(TraceObject.java:366)
at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:256)
at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
... 25 common frames omitted
Caused by: java.lang.NullPointerException: null
at org.h2.engine.Session.addTableToDependencies(Session.java:1874)
at org.h2.engine.Session.startStatementWithinTransaction(Session.java:1832)
at org.h2.command.Command.executeQuery(Command.java:190)
at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:233)
... 40 common frames omitted
2023-02-10 18:31:34.898 WARN  org.apache.ibatis.io.SerialFilterChecker : As you are using functionality that deserializes object streams, it is recommended to define the JEP-290 serial filter. Please refer to https://docs.oracle.com/pls/topic/lookup?ctx=javase15&id=GUID-8296D8E8-2B93-4B9A-856E-0A65AF9B8C66
`

**To Reproduce**
1. docker run -p 8080:8080 datart/datart
2. add data source type(FILE)
3. save

**Expected behavior**

**Screenshots**
<img width="658" alt="截屏2023-02-10 18 32 14" src="https://user-images.githubusercontent.com/12199008/218070606-ca813577-4390-4a3a-8061-4e3977cedf5a.png">

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: Mac 12.6.3 (21G419)
 - Source Database: Default
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by hongye007** [comment]
[参考](https://github.com/running-elephant/datart/pull/1701)
在采用h2数据库,并且事务隔离为 REPEATABLE_READ时, 由于默认的 ./bin/h2/datart.demo.mv.db里的 source_schemas缺少约束, 导致读取时出现空指针
source_schemas增加主键约束
alter table source_schemas ADD CONSTRAINT source_schemas_pk primary key (id);
ps：mysql是正常的，可以用mysql导出的数据库初始化一个H2，然后添加主键。

**Comment by hongye007** [comment]
[datart.demo.mv.db.zip](https://github.com/running-elephant/datart/files/10713896/datart.demo.mv.db.zip)
