### ISSUE TITLE
创建数据图表时 列转换为日期类型错误

### ISSUE THREAD

**Issue by zhu-mingye** [running-elephant/datart#583]
**Datart Version**
beta1

**Describe the bug**
![图片](https://user-images.githubusercontent.com/58576849/148924972-f83cdfbe-0933-470c-8ab8-add215a35db6.png)
创建查询是 (表中这两个字段类型为字符串) datart中设置转换为 日期类型 此处不报错

在创建 创建数据图表时  报错截图如下
![图片](https://user-images.githubusercontent.com/58576849/148925532-f5b389cd-b22f-47f6-b552-aa3acbc56551.png)

日志如下:
`
2022-01-11 18:24:02.181 [http-nio-192.168.0.204-11011-exec-2] ERROR datart.server.config.WebExceptionHandler : Cannot parse "DATE" constant "2017-10"; SQL statement:
CREATE TABLE IF NOT EXISTS `Qef2dd381b4bb331129292e4c52af284d` AS (SELECT * FROM FUNCTION_TABLE('DF5a00e05c38934d3288c203ef0df90c06')) [22007-200]
org.h2.jdbc.JdbcSQLDataException: Cannot parse "DATE" constant "2017-10"; SQL statement:
CREATE TABLE IF NOT EXISTS `Qef2dd381b4bb331129292e4c52af284d` AS (SELECT * FROM FUNCTION_TABLE('DF5a00e05c38934d3288c203ef0df90c06')) [22007-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.value.ValueDate.parse(ValueDate.java:74)
        at org.h2.value.Value.convertToDate(Value.java:1093)
        at org.h2.value.Value.convertTo(Value.java:816)
        at org.h2.value.Value.convertTo(Value.java:772)
        at org.h2.value.TypeInfo.cast(TypeInfo.java:515)
        at org.h2.table.Column.validateConvertUpdateSequence(Column.java:378)
        at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
        at org.h2.command.dml.Insert.addRow(Insert.java:249)
        at org.h2.command.dml.Select.queryFlat(Select.java:739)
        at org.h2.command.dml.Select.queryWithoutCache(Select.java:844)
        at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:201)
        at org.h2.command.dml.Query.query(Query.java:489)
        at org.h2.command.dml.Insert.insertRows(Insert.java:217)
        at org.h2.command.dml.Insert.update(Insert.java:151)
        at org.h2.command.ddl.CreateTable.update(CreateTable.java:145)
        at org.h2.command.CommandContainer.update(CommandContainer.java:198)
        at org.h2.command.Command.executeUpdate(Command.java:251)
        at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:240)
        at datart.data.provider.local.LocalDB.registerDataAsTable(LocalDB.java:143)
        at datart.data.provider.local.LocalDB.executeInMemDB(LocalDB.java:197)
        at datart.data.provider.local.LocalDB.executeLocalQuery(LocalDB.java:187)
        at datart.data.provider.local.LocalDB.executeLocalQuery(LocalDB.java:167)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.executeInLocal(JdbcDataProviderAdapter.java:321)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.execute(JdbcDataProviderAdapter.java:202)
        at datart.data.provider.JdbcDataProvider.execute(JdbcDataProvider.java:87)
        at datart.data.provider.ProviderManager.run(ProviderManager.java:188)
        at datart.data.provider.optimize.DataProviderExecuteOptimizer.runOptimize(DataProviderExecuteOptimizer.java:47)
        at datart.data.provider.ProviderManager.execute(ProviderManager.java:109)
        at datart.server.service.impl.DataProviderServiceImpl.execute(DataProviderServiceImpl.java:259)
        at datart.server.controller.DataProviderController.execute(DataProviderController.java:101)
        at sun.reflect.GeneratedMethodAccessor245.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 2017-10
        at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:157)
        at org.h2.value.ValueDate.parse(ValueDate.java:72)
        ... 78 common frames omitted

`

![图片](https://user-images.githubusercontent.com/58576849/148926435-ccbcff60-4b58-4cbd-8d59-72f8f2508437.png)

`
2022-01-11 18:28:53.349 [http-nio-192.168.0.204-11011-exec-8] ERROR datart.server.config.WebExceptionHandler : Cannot parse "DATE" constant "2017-10-26 03:35:45"; SQL statement:
CREATE TABLE IF NOT EXISTS `Qe1d6ccbc0b7f3d2307c3c8bebd2d1e46` AS (SELECT * FROM FUNCTION_TABLE('DFb0e7426f2f58430593e9d8547012b1c8')) [22007-200]
org.h2.jdbc.JdbcSQLDataException: Cannot parse "DATE" constant "2017-10-26 03:35:45"; SQL statement:
CREATE TABLE IF NOT EXISTS `Qe1d6ccbc0b7f3d2307c3c8bebd2d1e46` AS (SELECT * FROM FUNCTION_TABLE('DFb0e7426f2f58430593e9d8547012b1c8')) [22007-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.value.ValueDate.parse(ValueDate.java:74)
        at org.h2.value.Value.convertToDate(Value.java:1093)
        at org.h2.value.Value.convertTo(Value.java:816)
        at org.h2.value.Value.convertTo(Value.java:772)
        at org.h2.value.TypeInfo.cast(TypeInfo.java:515)
        at org.h2.table.Column.validateConvertUpdateSequence(Column.java:378)
        at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
        at org.h2.command.dml.Insert.addRow(Insert.java:249)
        at org.h2.command.dml.Select.queryFlat(Select.java:739)
        at org.h2.command.dml.Select.queryWithoutCache(Select.java:844)
        at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:201)
        at org.h2.command.dml.Query.query(Query.java:489)
        at org.h2.command.dml.Insert.insertRows(Insert.java:217)
        at org.h2.command.dml.Insert.update(Insert.java:151)
        at org.h2.command.ddl.CreateTable.update(CreateTable.java:145)
        at org.h2.command.CommandContainer.update(CommandContainer.java:198)
        at org.h2.command.Command.executeUpdate(Command.java:251)
        at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:240)
        at datart.data.provider.local.LocalDB.registerDataAsTable(LocalDB.java:143)
        at datart.data.provider.local.LocalDB.executeInMemDB(LocalDB.java:197)
        at datart.data.provider.local.LocalDB.executeLocalQuery(LocalDB.java:187)
        at datart.data.provider.local.LocalDB.executeLocalQuery(LocalDB.java:167)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.executeInLocal(JdbcDataProviderAdapter.java:321)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.execute(JdbcDataProviderAdapter.java:202)
        at datart.data.provider.JdbcDataProvider.execute(JdbcDataProvider.java:87)
        at datart.data.provider.ProviderManager.run(ProviderManager.java:188)
        at datart.data.provider.optimize.DataProviderExecuteOptimizer.runOptimize(DataProviderExecuteOptimizer.java:47)
        at datart.data.provider.ProviderManager.execute(ProviderManager.java:109)
        at datart.server.service.impl.DataProviderServiceImpl.execute(DataProviderServiceImpl.java:259)
        at datart.server.controller.DataProviderController.execute(DataProviderController.java:101)
        at sun.reflect.GeneratedMethodAccessor245.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: 26 03:35:45
        at org.h2.util.StringUtils.parseUInt31(StringUtils.java:1020)
        at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:171)
        at org.h2.value.ValueDate.parse(ValueDate.java:72)
        ... 78 common frames omitted

`

`
Cannot parse "DATE" constant "2017-10-26 03:35:45"; SQL statement: CREATE TABLE IF NOT EXISTS `Qe1d6ccbc0b7f3d2307c3c8bebd2d1e46` AS (SELECT * FROM FUNCTION_TABLE('DF781c27574caa46d587e409cf0ae2a6bb')) [22007-200]
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by tianlu-root** [comment]
1.0.0-beta.0版本经测试，'2017-10-26 03:35:45','2020/10','2001'等日期格式都正常解析，无法复现你的问题。能否在demo环境复现这个问题？

**Comment by YQChen-SYSU** [comment]
遇到相同的问题，请问是否解决了呢？
