### ISSUE TITLE
[dev] -[可视化] 查询报错

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#692]
**Datart Version**
dev
**Describe the bug**
数据源是clickhouse, 字段名少了``
![image](https://user-images.githubusercontent.com/83893570/151170846-39170443-7927-47dd-8928-58938e6d3008.png)

![image](https://user-images.githubusercontent.com/83893570/151171160-1620188e-a612-4b92-a8fd-861df40a38d3.png)

**Comment by tianlu-root** [comment]
这个报错不是SQL解析错误，最终生成的SQL有问题。方便提供一下包含完整SQL的报错信息吗？

**Comment by tianlu-root** [comment]
最新版本有做如下改动：对用户的SQL当中的字段，不会默认加引号。因为加上引号在某些数据库中会导致问题。所以如果你的表中有特殊字段名称，需要自己加上引号，或者通过别名的方式修改这个字段名称。

**Comment by Data-bytes305** [comment]
数据源
![image](https://user-images.githubusercontent.com/83893570/151546925-3e50d083-78aa-457f-8ed6-24699ee8d7f6.png)

图表
![image](https://user-images.githubusercontent.com/83893570/151547038-b3e11c82-dc53-4684-a21b-5193cdd1a675.png)

后台日志
ELECT DATART_VTABLE.id, DATART_VTABLE.名称 FROM  (select 1 as id , 'abc' as `名称`)  AS `DATART_VTABLE` GROUP BY DATART_VTABLE.id, DATART_VTABLE.名称 LIMIT 0, 100
2022-01-28 20:28:39.151 [http-nio-10.239.33.43-7080-exec-5] ERROR datart.server.config.WebExceptionHandler : ClickHouse exception, code: 1002, host: 168.30.16.99, port: 8123; Code: 62. DB::Exception: Syntax error: failed at position 40 ('�'): 名称 FROM  (select 1 as id , 'abc' as `名称`)  AS `DATART_VTABLE` GROUP BY DATART_VTABLE.id, DATART_VTABLE.名称 LIMIT 0, 100. Unrecognized token: '�'. (SYNTAX_ERROR) (version 22.1.2.2 (official build))

ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 168.30.16.99, port: 8123; Code: 62. DB::Exception: Syntax error: failed at position 40 ('�'): 名称 FROM  (select 1 as id , 'abc' as `名称`)  AS `DATART_VTABLE` GROUP BY DATART_VTABLE.id, DATART_VTABLE.名称 LIMIT 0, 100. Unrecognized token: '�'. (SYNTAX_ERROR) (version 22.1.2.2 (official build))

        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:92)
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:56)
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:29)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1094)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:773)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getLastInputStream(ClickHouseStatementImpl.java:691)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:340)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:324)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:319)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:314)
        at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:296)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.execute(JdbcDataProviderAdapter.java:193)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.executeOnSource(JdbcDataProviderAdapter.java:376)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.execute(JdbcDataProviderAdapter.java:234)
        at datart.data.provider.JdbcDataProvider.execute(JdbcDataProvider.java:87)
        at datart.data.provider.ProviderManager.run(ProviderManager.java:231)
        at datart.data.provider.optimize.DataProviderExecuteOptimizer.runOptimize(DataProviderExecuteOptimizer.java:47)
        at datart.data.provider.ProviderManager.execute(ProviderManager.java:119)
        at datart.server.service.impl.DataProviderServiceImpl.execute(DataProviderServiceImpl.java:260)
        at datart.server.controller.DataProviderController.execute(DataProviderController.java:101)
        at sun.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Throwable: Code: 62. DB::Exception: Syntax error: failed at position 40 ('�'): 名称 FROM  (select 1 as id , 'abc' as `名称`)  AS `DATART_VTABLE` GROUP BY DATART_VTABLE.id, DATART_VTABLE.名称 LIMIT 0, 100. Unrecognized token: '�'. (SYNTAX_ERROR) (version 22.1.2.2 (official build))

**Comment by Data-bytes305** [comment]
个人建议: 是否可以在“数据源”这边增加个选项 1. “字段是否引号” 2，引号是`还是单引号还是 双引号 ？
