### ISSUE TITLE
创建组织报错

### ISSUE THREAD

**Issue by yunfeng79** [running-elephant/datart#903]
datart-server-1.0.0-beta.1
创建组织 输入后页面跳转报错
2022-03-01 15:21:57.868 [http-nio-192.168.0.127-12080-exec-4] WARN  o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler datart.server.config.WebExceptionHandler#validateException(BindException)
java.lang.StackOverflowError: null
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:446)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:442)
	at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:448)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:358)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:338)
	at com.alibaba.fastjson.serializer.ObjectArrayCodec.write(ObjectArrayCodec.java:118)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:320)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:470)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:135)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:320)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:470)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:320)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:470)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:320)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:470)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:320)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:470)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:320)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:470)

2022-03-01 15:21:58.239 [http-nio-192.168.0.127-12080-exec-5] WARN  o.s.w.s.m.support.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public datart.server.base.dto.ResponseData<java.lang.Boolean> datart.server.controller.OrgController.checkOrgName(datart.server.base.params.CheckNameParam): [Field error in object 'checkNameParam' on field 'name': rejected value [ ]; codes [NotBlank.checkNameParam.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [checkNameParam.name,name]; arguments []; default message [name]]; default message [不能为空]] ]
2022-03-01 15:21:58.241 [http-nio-192.168.0.127-12080-exec-5] WARN  o.s.w.s.m.support.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]
2022-03-01 15:27:40.531 [http-nio-192.168.0.127-12080-exec-4] WARN  com.alibaba.druid.pool.DruidAbstractDataSource : discard long time none received connection. , jdbcUrl : jdbc:mysql://xx/datart?&allowMultiQueries=true, version : 1.2.4, lastPacketReceivedIdleMillis : 349387
2022-03-01 15:27:40.531 [http-nio-192.168.0.127-12080-exec-5] WARN  com.alibaba.druid.pool.DruidAbstractDataSource : discard long time none received connection. , jdbcUrl : jdbc:mysql://xx/datart?&allowMultiQueries=true, version : 1.2.4, lastPacketReceivedIdleMillis : 356257
2022-03-01 15:27:48.718 [http-nio-192.168.0.127-12080-exec-1] INFO  d.data.provider.jdbc.DataSourceFactoryDruidImpl : druid data source created (DataSource-4180908)
2022-03-01 15:27:48.867 [http-nio-192.168.0.127-12080-exec-1] ERROR com.alibaba.druid.pool.DruidDataSource : testWhileIdle is true, validationQuery not set
2022-03-01 15:27:48.867 [http-nio-192.168.0.127-12080-exec-1] INFO  com.alibaba.druid.pool.DruidDataSource : {dataSource-2} inited

**Comment by tianlu-root** [comment]
#1002
