### ISSUE TITLE
phoenix作数据源时，date以及timestamp类型的字段作为过滤条件时会报错

### ISSUE THREAD

**Issue by jinfeng202111** [running-elephant/datart#984]
phoenix作数据源时，date以及timestamp类型的字段作为过滤条件时，并且把数据分析中的数据聚合关闭时会报错Type mismatch. BOOLEAN and DATE for CNT_DATE或者 Type mismatch. BOOLEAN and TIMESTAMP for LAST_MOD_TIME_AMT。 当打开数据聚合时就正常了。全部报错日志如下：
ERROR datart.server.config.WebExceptionHandler : ERROR 203 (22005): Type mismatch. BOOLEAN and DATE for CNT_DATE
org.apache.phoenix.schema.TypeMismatchException: ERROR 203 (22005): Type mismatch. BOOLEAN and DATE for CNT_DATE
        at org.apache.phoenix.schema.TypeMismatchException.newException(TypeMismatchException.java:53)
        at org.apache.phoenix.expression.AndExpression.create(AndExpression.java:45)
        at org.apache.phoenix.compile.ExpressionCompiler.visitLeave(ExpressionCompiler.java:241)
        at org.apache.phoenix.compile.ExpressionCompiler.visitLeave(ExpressionCompiler.java:143)
        at org.apache.phoenix.parse.AndParseNode.accept(AndParseNode.java:49)
        at org.apache.phoenix.compile.WhereCompiler.compile(WhereCompiler.java:138)
        at org.apache.phoenix.compile.WhereCompiler.compile(WhereCompiler.java:108)
        at org.apache.phoenix.compile.QueryCompiler.compileSingleFlatQuery(QueryCompiler.java:629)
        at org.apache.phoenix.compile.QueryCompiler.compileSingleQuery(QueryCompiler.java:574)
        at org.apache.phoenix.compile.QueryCompiler.compileSelect(QueryCompiler.java:203)
        at org.apache.phoenix.compile.QueryCompiler.compile(QueryCompiler.java:157)
        at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableSelectStatement.compilePlan(PhoenixStatement.java:497)
        at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableSelectStatement.compilePlan(PhoenixStatement.java:460)
        at org.apache.phoenix.jdbc.PhoenixStatement$1.call(PhoenixStatement.java:303)
        at org.apache.phoenix.jdbc.PhoenixStatement$1.call(PhoenixStatement.java:292)
        at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
        at org.apache.phoenix.jdbc.PhoenixStatement.executeQuery(PhoenixStatement.java:291)
        at org.apache.phoenix.jdbc.PhoenixStatement.executeQuery(PhoenixStatement.java:284)
        at org.apache.phoenix.jdbc.PhoenixPreparedStatement.executeQuery(PhoenixPreparedStatement.java:193)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.executeCountSql(JdbcDataProviderAdapter.java:247)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.executeOnSource(JdbcDataProviderAdapter.java:385)
        at datart.data.provider.jdbc.adapters.JdbcDataProviderAdapter.execute(JdbcDataProviderAdapter.java:234)
        at datart.data.provider.JdbcDataProvider.execute(JdbcDataProvider.java:89)
        at datart.data.provider.ProviderManager.run(ProviderManager.java:231)
        at datart.data.provider.optimize.DataProviderExecuteOptimizer.runOptimize(DataProviderExecuteOptimizer.java:47)
        at datart.data.provider.ProviderManager.execute(ProviderManager.java:119)
        at datart.server.service.impl.DataProviderServiceImpl.execute(DataProviderServiceImpl.java:258)
        at datart.server.controller.DataProviderController.execute(DataProviderController.java:101)
        at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
![1646979283(1)](https://user-images.githubusercontent.com/94880167/157813119-1ef27319-56da-47e1-b8cb-1f1f018b62f8.png)
![1646979444(1)](https://user-images.githubusercontent.com/94880167/157813176-8293e9c9-23eb-43bd-8041-1b0bce050df9.png)

**Comment by tianlu-root** [comment]
可能是数据源数据的问题，需要提供一下报错时执行的SQL。在beta.2版本在执行报错时在[SQL]里也能看见执行的SQL，或者在任意版本的config/logback.xml里吧 SQL_LEVEL 的值改为DEBUG。 `<property name ="SQL_LEVEL" value="DEBUG"/>` 。然后在logs目录下就能看见执行的SQL。

**Comment by jinfeng202111** [comment]
2022-03-16 09:13:53.776 [http-nio-192.168.15.205-8093-exec-3] DEBUG d.d.provider.jdbc.adapters.JdbcDataProviderAdapter : SELECT "DATART_VTABLE"."COMP_CODE" AS "COMP_CODE", "DATART_VTABLE"."CNT_DATE" AS "CNT_DATE", "DATART_VTABLE"."CNT" AS "CNT", "DATART_VTABLE"."AMT" AS "AMT" FROM  ( select   COMP_CODE,   CNT_DATE,   CNT,   AMT,   ZJF_PT_CNT,   ZJF_PT_AMT,   ZJF_YH_CNT,   ZJF_YH_AMT,   SHY_XH_CNT,   SHY_XH_AMT,   SHY_DY_CNT,   SHY_DY_AMT,   ZJF_PT_AMT_BL,   ZJF_YH_AMT_BL,   SHY_XH_AMT_BL,   SHY_DY_AMT_BL from   GBU_DWS_CREDIT.DWS_EC_CREDIT_COUNT )  AS "DATART_VTABLE" WHERE "CNT_DATE" BETWEEN TIMESTAMP '2022-01-01 00:00:00' AND TIMESTAMP '2022-12-31 23:59:59'

**Comment by jinfeng202111** [comment]
> 可能是数据源数据的问题，需要提供一下报错时执行的SQL。在beta.2版本在执行报错时在[SQL]里也能看见执行的SQL，或者在任意版本的config/logback.xml里吧 SQL_LEVEL 的值改为DEBUG。 `<property name ="SQL_LEVEL" value="DEBUG"/>` 。然后在logs目录下就能看见执行的SQL。

2022-03-16 09:13:53.776 [http-nio-192.168.15.205-8093-exec-3] DEBUG d.d.provider.jdbc.adapters.JdbcDataProviderAdapter : SELECT "DATART_VTABLE"."COMP_CODE" AS "COMP_CODE", "DATART_VTABLE"."CNT_DATE" AS "CNT_DATE", "DATART_VTABLE"."CNT" AS "CNT", "DATART_VTABLE"."AMT" AS "AMT" FROM  ( select   COMP_CODE,   CNT_DATE,   CNT,   AMT,   ZJF_PT_CNT,   ZJF_PT_AMT,   ZJF_YH_CNT,   ZJF_YH_AMT,   SHY_XH_CNT,   SHY_XH_AMT,   SHY_DY_CNT,   SHY_DY_AMT,   ZJF_PT_AMT_BL,   ZJF_YH_AMT_BL,   SHY_XH_AMT_BL,   SHY_DY_AMT_BL from   GBU_DWS_CREDIT.DWS_EC_CREDIT_COUNT )  AS "DATART_VTABLE" WHERE "CNT_DATE" BETWEEN TIMESTAMP '2022-01-01 00:00:00' AND TIMESTAMP '2022-12-31 23:59:59'

**Comment by jinfeng202111** [comment]
已解决，我将数据源的服务端聚合开启后就解决了
![b9949f8b162e9084ed99172329e05c8](https://user-images.githubusercontent.com/94880167/158730710-51682e4b-dba6-47c6-87c2-fb5557b86116.png)

**Comment by scottsut** [comment]
@jinfeng202111 服务端聚合的支持场景是有限的，它使用 datart 服务器的内存进行计算，数据量大的情况下是不适合的，建议还是从正确的角度来定位和解决问题

**Comment by jinfeng202111** [comment]
> @jinfeng202111 服务端聚合的支持场景是有限的，它使用 datart 服务器的内存进行计算，数据量大的情况下是不适合的，建议还是从正确的角度来定位和解决问题

是的。其实服务端聚合没有开启之前，不仅仅时这一个问题，还有很多其他的问题，但是开启之后这些问题都没有了，所以还得需要各位加把劲解决bug了。

**Comment by jinfeng202111** [comment]
> @jinfeng202111 服务端聚合的支持场景是有限的，它使用 datart 服务器的内存进行计算，数据量大的情况下是不适合的，建议还是从正确的角度来定位和解决问题

接上面:
我使用Mysql作为jdbc数据源时，数据源处没有开启服务端聚合，可视化处将date类型字段作为查询条件时，也没有打开数据聚合，但是就没有报错，而改为phoenix作为数据源时其他情况都相同，就会报错，麻烦跟进下这个bug哈

**Comment by jinfeng202111** [comment]
> @jinfeng202111 服务端聚合的支持场景是有限的，它使用 datart 服务器的内存进行计算，数据量大的情况下是不适合的，建议还是从正确的角度来定位和解决问题

接上面:
我使用Mysql作为jdbc数据源时，数据源处没有开启服务端聚合，可视化处将date类型字段作为查询条件时，也没有打开数据聚合，但是就没有报错，而改为phoenix作为数据源时其他情况都相同，就会报错，麻烦跟进下这个bug哈
